### PR TITLE
fix: add tests to demonstrate that PostCSS configs are not reused across projects

### PR DESCRIPTION
**Pull request by fwouts**
### Description

This sets up two separate apps with conflicting PostCSS configs, along with tests to make sure that each gets only its own CSS applied.

### Additional context

See https://github.com/vitejs/vite/pull/3906 for the original PR.

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/.github/contributing.md).
- [x] Read the [Pull Request Guidelines](https://github.com/vitejs/vite/blob/main/.github/contributing.md#pull-request-guidelines) and follow the [Commit Convention](https://github.com/vitejs/vite/blob/main/.github/commit-convention.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by fwouts** [comment]
@patak-js here are some tests for the PostCSS config caching PR. Let me know what you think about this approach, happy to reshuffle things around.

**Comment by Y1D7NG** [comment]
@fwouts  Thank you very much for the test. But I found that even if the original PR code is not included, the test can still be executed successfully in the current vite project.

**Comment by fwouts** [comment]
Hey @OneNail, thanks for catching this. I could have sworn I had run these tests without your commit and confirmed they failed!

I've been debugging this for an hour and I can't figure out what's going on. It looks like Jest is reloading modules between tests and resetting the value of `cachedPostcssConfig` every time, even when running with `--runInBand` which I've confirmed reuses the same process.

I ended up implementing it with a different approach to guarantee that it won't happen.

**Comment by Y1D7NG** [comment]
@fwouts Thank you very much for the test. If the original PR code isn't included, the test failed at

 ```expect(await getColor(blueA)).toBe('blue')```

 is it supposed to failed at

```expect(await getColor(greenB)).toBe('green')```

?

**Comment by fwouts** [comment]
> @fwouts Thank you very much for the test. If the original PR code isn't included, the test failed at
> 
> `expect(await getColor(blueA)).toBe('blue')`
> 
> is it supposed to failed at
> 
> `expect(await getColor(greenB)).toBe('green')`
> 
> ?

No, that's expected! That's because there's already another Vite server running (the one set up in https://github.com/vitejs/vite/blob/main/scripts/jestPerTestSetup.ts) so a `null` PostCSS config has already been cached. Therefore, even the first app fails.

I preferred to have both the blue and green app so we don't rely on this implicit behaviour :)

**Comment by Y1D7NG** [comment]
@fwouts Thank you very much, I merged the commit.

**Pull request merged**
